"""Non-configurable storage safety ceilings for public mutation paths."""

MAX_CHALLENGE_ATTEMPTS = 1_000
MAX_SUBMISSIONS_PER_TEAM_EVENT = 10_000
MAX_TEAM_MUTATIONS_PER_USER_EVENT = 100
MAX_MEMBERS_PER_TEAM = 100
MAX_PARTICIPANT_USERS = 100_000
MAX_ACTIVE_SESSIONS_PER_USER = 10
MAX_PUBLIC_SCOREBOARD_ENTRIES = 1_000
SCOREBOARD_BUILD_LEASE_SECONDS = 45
