#!/usr/bin/env python3
"""Verify that backend hash locks still describe pyproject.toml.

The lock resolver remains the authority for transitive packages. This check
guards the review-time failure mode where a direct dependency is changed but
the generated locks or Docker/CI installation path are not updated.
"""

from __future__ import annotations

import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name
from packaging.version import Version


APP_ROOT = Path(__file__).resolve().parent.parent
BACKEND = APP_ROOT / "backend"
PROJECT_ANNOTATION = "alpha-ctf-backend (backend/pyproject.toml)"
BUILD_ANNOTATION = "alpha-ctf-backend (backend/pyproject.toml::build-system.requires)"
ENTRY = re.compile(r"(?m)^([A-Za-z0-9_.-]+)==([^\s\\]+)")
HASH = re.compile(r"--hash=sha256:[0-9a-f]{64}(?:\s*\\)?$")


@dataclass(frozen=True)
class LockEntry:
    name: str
    version: Version
    block: str


def parse_lock(path: Path) -> tuple[dict[str, LockEntry], set[str]]:
    text = path.read_text(encoding="utf-8")
    if "autogenerated by pip-compile with Python 3.12" not in text:
        raise ValueError(f"{path.name}: pip-compile/Python 3.12 생성 header가 없습니다")
    if "--generate-hashes" not in text:
        raise ValueError(f"{path.name}: hash 생성 옵션이 header에 없습니다")
    if "--index-url" in text or "--trusted-host" in text:
        raise ValueError(f"{path.name}: repository 주소를 lock에 내장하지 마세요")

    matches = list(ENTRY.finditer(text))
    if not matches:
        raise ValueError(f"{path.name}: exact package pin이 없습니다")

    entries: dict[str, LockEntry] = {}
    annotated_direct: set[str] = set()
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        block = text[match.start() : end]
        name = canonicalize_name(match.group(1))
        if name in entries:
            raise ValueError(f"{path.name}: 중복 package pin: {name}")
        if not any(HASH.search(line.strip()) for line in block.splitlines()):
            raise ValueError(f"{path.name}: hash가 없는 package pin: {name}")
        entries[name] = LockEntry(name=name, version=Version(match.group(2)), block=block)
        if PROJECT_ANNOTATION in block or BUILD_ANNOTATION in block:
            annotated_direct.add(name)
    return entries, annotated_direct


def requirement_map(raw: list[str]) -> dict[str, Requirement]:
    result: dict[str, Requirement] = {}
    for value in raw:
        requirement = Requirement(value)
        name = canonicalize_name(requirement.name)
        if name in result:
            raise ValueError(f"pyproject.toml에 직접 의존성이 중복되었습니다: {name}")
        result[name] = requirement
    return result


def check_direct(
    label: str,
    entries: dict[str, LockEntry],
    annotated: set[str],
    expected: dict[str, Requirement],
) -> list[str]:
    errors: list[str] = []
    expected_names = set(expected)
    if annotated != expected_names:
        missing = sorted(expected_names - annotated)
        stale = sorted(annotated - expected_names)
        if missing:
            errors.append(f"{label}: lock direct annotation 누락: {', '.join(missing)}")
        if stale:
            errors.append(f"{label}: pyproject에서 제거된 direct annotation: {', '.join(stale)}")
    for name, requirement in expected.items():
        entry = entries.get(name)
        if entry is None:
            errors.append(f"{label}: 직접 의존성 pin 누락: {name}")
        elif entry.version not in requirement.specifier:
            errors.append(
                f"{label}: {name}=={entry.version}이 선언 범위 {requirement.specifier} 밖입니다"
            )
    return errors


def main() -> int:
    pyproject = tomllib.loads((BACKEND / "pyproject.toml").read_text(encoding="utf-8"))
    runtime_expected = requirement_map(pyproject["project"]["dependencies"])
    test_expected = requirement_map(
        pyproject["project"]["dependencies"]
        + pyproject["project"]["optional-dependencies"]["test"]
    )
    build_expected = requirement_map(pyproject["build-system"]["requires"])

    locks: dict[str, tuple[dict[str, LockEntry], set[str]]] = {}
    errors: list[str] = []
    for label, filename in (
        ("runtime", "requirements.lock"),
        ("test", "requirements-test.lock"),
        ("build", "requirements-build.lock"),
    ):
        try:
            locks[label] = parse_lock(BACKEND / filename)
        except (OSError, ValueError) as exc:
            errors.append(str(exc))

    if errors:
        print("backend lock 검증 실패:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    runtime_entries, runtime_annotated = locks["runtime"]
    test_entries, test_annotated = locks["test"]
    build_entries, build_annotated = locks["build"]
    errors.extend(check_direct("runtime", runtime_entries, runtime_annotated, runtime_expected))
    errors.extend(check_direct("test", test_entries, test_annotated, test_expected))
    errors.extend(check_direct("build", build_entries, build_annotated, build_expected))

    for name, runtime_entry in runtime_entries.items():
        test_entry = test_entries.get(name)
        if test_entry is None:
            errors.append(f"test lock에 runtime package가 없습니다: {name}")
        elif test_entry.version != runtime_entry.version:
            errors.append(
                f"runtime/test pin 불일치: {name} {runtime_entry.version} != {test_entry.version}"
            )

    if errors:
        print("backend lock 검증 실패:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print(
        "backend lock 검증 통과: "
        f"runtime {len(runtime_entries)}, test {len(test_entries)}, build {len(build_entries)} pins"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
